
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rifki fikri
 */
public class TambahKurang extends javax.swing.JFrame {

    /**
     * Creates new form TambahKurang
     */
    public TambahKurang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1_282 = new javax.swing.JLabel();
        jLabel2_282 = new javax.swing.JLabel();
        jTextField1_282 = new javax.swing.JTextField();
        jButton1_282 = new javax.swing.JButton();
        jButton2_282 = new javax.swing.JButton();
        jLabel3_282 = new javax.swing.JLabel();
        jTextField2_282 = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_282.setText("Program Progres Nilai");

        jLabel2_282.setText("Masukkan Nilai");

        jButton1_282.setText("Kurangi");
        jButton1_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_282ActionPerformed(evt);
            }
        });

        jButton2_282.setText("Tambah");
        jButton2_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_282ActionPerformed(evt);
            }
        });

        jLabel3_282.setText("Hasil");

        jTextField2_282.setEditable(false);
        jTextField2_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_282ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_282)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1_282)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2_282))
                            .addComponent(jLabel3_282)
                            .addComponent(jTextField2_282, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1_282, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)))
                    .addComponent(jTextField1_282, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1_282)
                .addGap(18, 18, 18)
                .addComponent(jLabel2_282)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1_282, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_282)
                    .addComponent(jButton2_282))
                .addGap(30, 30, 30)
                .addComponent(jLabel3_282)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2_282, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int hasil=0;
    private void jButton1_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_282ActionPerformed
        // TODO add your handling code here:
        String angka=jTextField1_282.getText();
        int keluar=Integer.parseInt(angka);
        
        hasil=hasil-keluar;
         if(hasil<=0){
            JOptionPane.showMessageDialog(null, "Nilai hasil tidak boleh dibawah 0");
        }else if(hasil>100){
            JOptionPane.showMessageDialog(null, "Nilai hasil Tidak boleh di atas 100");
        }
        jTextField2_282.setText(" "+hasil);
    }//GEN-LAST:event_jButton1_282ActionPerformed
    
    private void jButton2_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_282ActionPerformed
        // TODO add your handling code here:
        
        String angka=jTextField1_282.getText();
        int keluar=Integer.parseInt(angka);
        
        hasil=hasil+keluar;
         if(hasil<=0){
            JOptionPane.showMessageDialog(null, "Nilai hasil tidak boleh dibawah 0");
        }else if(hasil>100){
            JOptionPane.showMessageDialog(null, "Nilai Tidak boleh di atas 100");
        }
        jTextField2_282.setText(" "+hasil);
    }//GEN-LAST:event_jButton2_282ActionPerformed

    private void jTextField2_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_282ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField2_282ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahKurang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahKurang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahKurang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahKurang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahKurang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_282;
    private javax.swing.JButton jButton2_282;
    private javax.swing.JLabel jLabel1_282;
    private javax.swing.JLabel jLabel2_282;
    private javax.swing.JLabel jLabel3_282;
    private javax.swing.JTextField jTextField1_282;
    private javax.swing.JTextField jTextField2_282;
    // End of variables declaration//GEN-END:variables
}
